---
title: "Dashboard - Suicidio"
author: "Valeska Alves"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: scroll
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(readr)
library(dplyr)
library(shiny)
```

```{r}
df <- read.csv("../Datos/filtered_df.csv")
```

```{r, include=FALSE}
anos <- unique(df$time)
paises <- unique(df$country_name)
idades <- c("suicide_0_14", "suicide_15_29", "suicide_30_44", "suicide_45_59", "suicide_60plus")
generos <- c("suicide_men", "suicide_women")
anos_categoria <- c("Todos", "1955 a 1969", "1970 a 1984", "1985 a 1999","2000 a 2015")

# Definir cores fixas para cada país
custom_colors <- c(
  "Estados Unidos" = "deepskyblue",
  "Reino Unido" = "mediumslateblue",
  "Japón" = "palegreen",
  "Francia" = "chocolate",
  "Canadá" = "orchid",
  "España" = "firebrick"
)
```

**Filtros**

```{r}
fluidRow(
  column(3, selectInput("ano", "Ano:", choices = c("Todos", anos), selected = "Todos")),
  column(3, selectInput("pais", "País:", choices = c("Todos", paises), selected = "Todos")),
  column(3, selectInput("idade", "Idade:", choices = c("Todos", idades), selected = "Todos")),
  column(3, selectInput("genero", "Gênero:", choices = c("Todos", generos), selected = "Todos"))
)
```

**Datos de Suicidio de los principales países del mundo**

Column {data-width=500}
-----------------------------------------------------------------------

### Número Total de Suicidio por País

```{r}
renderPlot({
  filtered_data <- df
  
  if (input$ano != "Todos") {
    filtered_data <- filtered_data %>% filter(time == input$ano)
  }
  if (input$pais != "Todos") {
    filtered_data <- filtered_data %>% filter(country_name == input$pais)
  }
  if (input$idade != "Todos") {
    filtered_data <- filtered_data %>% filter(!is.na(!!sym(input$idade)))
  }
  if (input$genero != "Todos") {
    filtered_data <- filtered_data %>% filter(!is.na(!!sym(input$genero)))
  }
  
  summary_data <- filtered_data %>%
    group_by(country_name) %>%
    summarise(suicide_total = sum(suicide_total, na.rm = TRUE))
  
  ggplot(summary_data, aes(x = reorder(country_name, suicide_total), y = suicide_total, fill=country_name)) +
    geom_bar(stat = "identity") +
    geom_text(aes(label = suicide_total), vjust = -0.5, size = 3) +
    labs(x = "País", y = "Número Total de Suicidios") +
    scale_fill_manual(values = custom_colors) +
    theme_minimal() +
    theme(axis.text.x = element_text(angle = 45, hjust = 1))
})
```

### Tasas Promedio de Suicidio por Edad

```{r}
fluidRow(
  column(12, selectInput("ano_categoria_edad", "Categoria de Ano:", choices = anos_categoria, selected = "Todos"))
)
renderPlot({
  filtered_data <- df
  
  if (input$ano_categoria_edad != "Todos") {
    filtered_data <- filtered_data %>% filter(year_category == input$ano_categoria_edad)
  }
  if (input$pais != "Todos") {
    filtered_data <- filtered_data %>% filter(country_name == input$pais)
  }
  if (input$idade != "Todos") {
    filtered_data <- filtered_data %>% filter(!is.na(!!sym(input$idade)))
  }
  if (input$genero != "Todos") {
    filtered_data <- filtered_data %>% filter(!is.na(!!sym(input$genero)))
  }
  
  filtered_data %>%
    gather(key = "age_group", value = "suicides", suicide_0_14:suicide_60plus) %>%
    filter(!is.na(suicides)) %>%
    group_by(age_group) %>%
    summarise(mean_suicides = mean(suicides, na.rm = TRUE)) %>%
    ggplot(aes(x = age_group, y = mean_suicides, fill="steelblue")) +
    geom_bar(stat = "identity") +
    geom_text(aes(label = round(mean_suicides, 1)), vjust = -0.5, size = 3) + 
    labs(x = "Faixa Etária", y = "Tasa de Suicidio (por 100000 personas)") +
    scale_fill_manual(values = "steelblue") +
    theme_minimal() +
    theme(
      legend.position = "none",
      axis.text.x = element_text(angle = 45, hjust = 1),
      plot.margin = unit(c(1, 1, 1, 1), "cm") # Ajuste das margens
    )
}, height = 400)# Ajuste da altura do gráfico
```



### Correlación de Tasa de Suicidio y Edad

```{r}
renderPlot({
  observeEvent(input$reset, {
    updateSelectInput(session, "ano", selected = "Todos")
    updateSelectInput(session, "pais", selected = "Todos")
    updateSelectInput(session, "idade", selected = "Todos")
    updateSelectInput(session, "genero", selected = "Todos")
  })
  
  filtered_data <- df
  
  if (input$ano != "Todos") {
    filtered_data <- filtered_data %>% filter(time == input$ano)
  }
  if (input$pais != "Todos") {
    filtered_data <- filtered_data %>% filter(country_name == input$pais)
  }
  if (input$idade != "Todos") {
    filtered_data <- filtered_data %>% filter(!is.na(!!sym(input$idade)))
  }
  if (input$genero != "Todos") {
    filtered_data <- filtered_data %>% filter(!is.na(!!sym(input$genero)))
  }

  # Gerar o gráfico de correlação
  filtered_data %>%
    gather(key = "age_group", value = "suicides", suicide_0_14:suicide_60plus) %>%
    filter(!is.na(suicides)) %>%
    ggplot(aes(x = age_group, y = suicides)) +
    geom_point(aes(color = country_name)) +
    geom_smooth(method = "lm", se = FALSE) +
    scale_color_manual(values = custom_colors) +
    labs(x = "Faixa Etária", y = "Tasa de Suicidio (por 100000 personas)") +
    theme_minimal() +
    theme(axis.text.x = element_text(angle = 45, hjust = 1),
          plot.margin = margin(10, 10, 10, 10)) # Ajusta as margens do gráfico
}, height = 400) # Ajusta a altura do gráfico
```

### Análisis de Valores Atípicos por País

```{r}
fluidRow(
  column(12, selectInput("ano_categoria", "Categoria de Ano:", choices = anos_categoria, selected = "Todos"))
)

renderPlot({
  observeEvent(input$reset, {
    updateSelectInput(session, "ano_categoria", selected = "Todos")
    updateSelectInput(session, "pais", selected = "Todos")
    updateSelectInput(session, "idade", selected = "Todos")
    updateSelectInput(session, "genero", selected = "Todos")
  })
  
  filtered_data <- df
  
  if (!is.null(input$ano_categoria) && input$ano_categoria != "Todos") {
    filtered_data <- filtered_data %>% filter(year_category == input$ano_categoria)
    print(paste("Filtrando por ano_categoria:", input$ano_categoria))
    print(head(filtered_data))
  }
  if (!is.null(input$pais) && input$pais != "Todos") {
    filtered_data <- filtered_data %>% filter(country_name == input$pais)
    print(paste("Filtrando por país:", input$pais))
    print(head(filtered_data))
  }
  if (!is.null(input$idade) && input$idade != "Todos") {
    filtered_data <- filtered_data %>% filter(!is.na(!!sym(input$idade)))
    print(paste("Filtrando por idade:", input$idade))
    print(head(filtered_data))
  }
  if (!is.null(input$genero) && input$genero != "Todos") {
    filtered_data <- filtered_data %>% filter(!is.na(!!sym(input$genero)))
    print(paste("Filtrando por gênero:", input$genero))
    print(head(filtered_data))
  }
  
  # Gerar os boxplots
  filtered_data %>%
    gather(key = "age_group", value = "suicides", suicide_0_14:suicide_60plus) %>%
    filter(!is.na(suicides)) %>%
    ggplot(aes(x = factor(time), y = suicides)) +
    geom_boxplot(aes(fill = country_name)) +
    labs(x = "Ano", y = "Tasa de Suicidio (por 100000 personas)") +
    scale_fill_manual(values = custom_colors) + 
    theme_minimal() +
    theme(axis.text.x = element_text(angle = 45, hjust = 1),
          plot.margin = unit(c(1, 1, 1, 1), "cm") # Ajuste das margens
    )
}, height = 400)
```

Column {data-width=500}
-----------------------------------------------------------------------

### Tasas Promedio de Suicidio por Año y por País

```{r}
renderPlot({
  observeEvent(input$reset, {
    updateSelectInput(session, "ano", selected = "Todos")
    updateSelectInput(session, "pais", selected = "Todos")
    updateSelectInput(session, "idade", selected = "Todos")
    updateSelectInput(session, "genero", selected = "Todos")
  })
  
  filtered_data <- df
  
  if (input$ano != "Todos") {
    filtered_data <- filtered_data %>% filter(time == input$ano)
  }
  if (input$pais != "Todos") {
    filtered_data <- filtered_data %>% filter(country_name == input$pais)
  }
  if (input$idade != "Todos") {
    filtered_data <- filtered_data %>% filter(!is.na(!!sym(input$idade)))
  }
  if (input$genero != "Todos") {
    filtered_data <- filtered_data %>% filter(!is.na(!!sym(input$genero)))
  }
  

ggplot(filtered_data %>% 
         group_by(time, country_name) %>% 
         summarise(mean_suicide_total = mean(suicide_total, na.rm = TRUE)), 
       aes(x = time, y = mean_suicide_total, color = country_name)) +
  geom_line() +
  scale_color_manual(values = custom_colors) +
  labs(x = "Ano", y = "Taxa Média de Suicídio (por 100000 pessoas)") +
  theme_minimal()
})

```


### Tasas Promedio de Suicidio por Género

```{r}
fluidRow(
  column(12, selectInput("ano_categoria_genero", "Categoria de Ano:", choices = anos_categoria, selected = "Todos"))
)
renderPlot({
  filtered_data <- df
  
  if (!is.null(input$ano_categoria_genero) && input$ano_categoria_genero != "Todos") {
    filtered_data <- filtered_data %>% filter(year_category == input$ano_categoria_genero)
  }
  if (!is.null(input$pais) && input$pais != "Todos") {
    filtered_data <- filtered_data %>% filter(country_name == input$pais)
  }
  if (!is.null(input$idade) && input$idade != "Todos") {
    filtered_data <- filtered_data %>% filter(!is.na(!!sym(input$idade)))
  }
  if (!is.null(input$genero) && input$genero != "Todos") {
    filtered_data <- filtered_data %>% filter(!is.na(!!sym(input$genero)))
  }
  
  filtered_data %>%
    gather(key = "gender", value = "suicides", suicide_men, suicide_women) %>%
    filter(!is.na(suicides)) %>%
    group_by(gender) %>%
    summarise(mean_suicides = mean(suicides, na.rm = TRUE)) %>%
    ggplot(aes(x = gender, y = mean_suicides, fill = gender)) +
    geom_text(aes(label = round(mean_suicides, 1)), vjust = -0.5, size = 3) + 
    geom_bar(stat = "identity", position = "dodge") +
    labs(x = "Género", y = "Tasa de Suicidio (por 100000 personas)") +
    theme_minimal() +
    scale_x_discrete(labels = function(x) gsub("\\.", " - ", x)) +
    theme(axis.text.x = element_text(angle = 45, hjust = 1),
          plot.margin = unit(c(1, 1, 1, 1), "cm") # Ajuste das margens
    )
}, height = 400)
```

### Correlación de Tasa de Suicidio y Género

```{r}
renderPlot({
  observeEvent(input$reset, {
    updateSelectInput(session, "ano_categoria", selected = "Todos")
    updateSelectInput(session, "ano", selected = "Todos")
    updateSelectInput(session, "pais", selected = "Todos")
    updateSelectInput(session, "idade", selected = "Todos")
    updateSelectInput(session, "genero", selected = "Todos")
  })
  
  filtered_data <- df
  
  if (!is.null(input$ano_categoria) && input$ano_categoria != "Todos") {
    filtered_data <- filtered_data %>% filter(year_category == input$ano_categoria)
  }
  if (!is.null(input$ano) && input$ano != "Todos") {
    filtered_data <- filtered_data %>% filter(time == input$ano)
  }
  if (!is.null(input$pais) && input$pais != "Todos") {
    filtered_data <- filtered_data %>% filter(country_name == input$pais)
  }
  if (!is.null(input$idade) && input$idade != "Todos") {
    filtered_data <- filtered_data %>% filter(!is.na(!!sym(input$idade)))
  }
  if (!is.null(input$genero) && input$genero != "Todos") {
    filtered_data <- filtered_data %>% filter(!is.na(!!sym(input$genero)))
  }

  # Gerar o gráfico de correlação
  filtered_data %>%
    gather(key = "gender", value = "suicides", suicide_men, suicide_women) %>%
    filter(!is.na(suicides)) %>%
    ggplot(aes(x = gender, y = suicides, color = gender)) +
    geom_point(aes(color = country_name)) +
    geom_smooth(method = "lm", se = FALSE) +
    scale_color_manual(values = custom_colors) +
    labs(x = "Gênero", y = "Tasa de Suicidio (por 100000 personas)") +
    theme_minimal() +
    theme(axis.text.x = element_text(angle = 45, hjust = 1))
})
```


### Correlación de Tasa de Suicidio y Países

```{r}
renderPlot({
  observeEvent(input$reset, {
    updateSelectInput(session, "ano", selected = "Todos")
    updateSelectInput(session, "pais", selected = "Todos")
    updateSelectInput(session, "idade", selected = "Todos")
    updateSelectInput(session, "genero", selected = "Todos")
  })
  
  filtered_data <- df
  
  if (input$ano != "Todos") {
    filtered_data <- filtered_data %>% filter(time %in% input$ano)
  }
  if (input$pais != "Todos") {
    filtered_data <- filtered_data %>% filter(country_name %in% input$pais)
  }
  if (input$idade != "Todos") {
    filtered_data <- filtered_data %>% filter(!is.na(!!sym(input$idade)))
  }
  if (input$genero != "Todos") {
    filtered_data <- filtered_data %>% filter(!is.na(!!sym(input$genero)))
  }

  # Generar el gráfico de correlación
  filtered_data %>%
    ggplot(aes(x = country_name, y = suicide_total)) +
    geom_point(aes(color = country_name)) +
    geom_smooth(method = "lm", se = FALSE) +
    scale_color_manual(values = custom_colors) +
    labs(x = "Países", y = "Tasa de Suicidio (por 100000 personas)") +
    theme_minimal() +
    theme(axis.text.x = element_text(angle = 45, hjust = 1))
})
```
