```{r setup, include=FALSE}
library(tidyverse)
library(readr)
library(dplyr)
```

```{r}
df <- read.csv("merged_df.csv")
```



```{r, warning=FALSE}
# Filtrar los datos para incluir solo los años de 1955 a 2015
df <- df %>% filter(time >= 1955 & time <= 2015)

# Dividir los años en hasta 5 períodos
df <- df %>% 
  mutate(year_category = case_when(
    time >= 1955 & time <= 1969 ~ "1955 a 1969",
    time >= 1970 & time <= 1984 ~ "1970 a 1984",
    time >= 1985 & time <= 1999 ~ "1985 a 1999",
    time >= 2000 & time <= 2015 ~ "2000 a 2015",
  ))

# Exibir os 10 países mais influentes
top_countries <- c("usa", "gbr", "jpn", "fra", "can", "esp")
geo_names <- c("usa" = "Estados Unidos", "gbr" = "Reino Unido", "jpn" = "Japón", 
               "fra" = "Francia", "can" = "Canadá", "esp" = "España")

filtered_df <- df %>% filter(geo %in% top_countries)
filtered_df <- filtered_df %>% mutate(country_name = geo_names[geo])
```  

```{r}
head(filtered_df)
```


```{r, warning=FALSE}
# Nome do arquivo CSV de saída
output_file <- "filtered_df.csv"

# Exportar o dataframe para um arquivo CSV
write.csv(filtered_df, file = output_file, row.names = FALSE)
```